on:
  release:
    types: [created]


env:
  BUILD_REPO: sozu-proxy/sozu


jobs:
  release:
    name: release ${{ matrix.target }}
    if: github.event_name == 'release'
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.BUILD_REPO }}
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          rustup target add ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target-dir=/tmp
      - name: Debug missing files
        run: |
          echo "target dir:"
          ls -a /tmp/release
          echo "deps:"
          ls -a /tmp/release/deps
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            /tmp/release